---
name: Nápady
about: Sdílejte své nápady a návrhy na vylepšení projektu.
title: '[Nápad] '
labels: idea
---

## Popis nápadu

Napište, co byste rádi viděli nebo vylepšili.

## Proč je tento nápad důležitý?

Popište, jaký přínos by měl tento nápad pro projekt nebo komunitu.

## Jak by se to dalo realizovat?

Pokud máte nějaký návrh řešení, napište ho sem.

---

**Děkujeme za vaše nápady!**  
Vaše návrhy nám pomáhají projekt zlepšovat.