---
name: Oznámení
about: Oficiální aktuality a oznámení od správců projektu.
title: '[Oznámení] '
labels: announcement
---

## Co je nového?

Napište zde důležité novinky, aktualizace nebo oznámení týkající se projektu.

## Detaily

Zde můžete přidat podrobnější informace, odkazy na nové funkce, opravy nebo jiné důležité zprávy.

---

Děkujeme, že sledujete náš projekt!
