name: 游댢 Refaktoring
description: Zlep코en칤 struktury nebo kvality k칩du bez zm캩ny jeho chov치n칤
title: "[Refaktoring] "
labels: ["typ:refaktoring"]
body:
  - type: textarea
    id: scope
    attributes:
      label: Co je pot콏eba refaktorovat?
      placeholder: "Kter치 캜치st k칩du a pro캜?"
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Pro캜 je to pot콏eba?
      placeholder: "Lep코칤 캜itelnost, v칳kon, testovatelnost..."
