version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:20.17
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: corepack enable && pnpm install
      - run:
          name: Lint
          command: pnpm lint
      - run:
          name: Type check
          command: pnpm typecheck
      - run:
          name: Build Next.js
          command: pnpm build

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
