name: Kontrola labelu u pull requestu

on:
  pull_request:
    types: [opened, reopened, labeled, unlabeled]

jobs:
  kontrola-labelu:
    runs-on: ubuntu-latest
    steps:
      - name: Zkontroluj, zda má PR nějaký label
        uses: actions/github-script@v7
        with:
          script: |
            const labels = context.payload.pull_request.labels;
            if (labels.length === 0) {
              core.setFailed("❌ Pull request musí mít alespoň jeden label.");
            } else {
              console.log(`✅ Pull request má následující label${labels.length > 1 ? 'y' : ''}: ${labels.map(l => l.name).join(", ")}`);
            }
