name: Kontrola kódu

on:
  push:
  pull_request:

jobs:
  test:
    name: Test + Lint + Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout kódu
        uses: actions/checkout@v4

      - name: Nastavení pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Nastavení Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.9.0"
          cache: "pnpm"

      - name: Instalace závislostí
        run: pnpm install

      - name: Vygenerování Prisma klienta
        run: npx prisma generate

      - name: Spuštění linteru
        run: pnpm lint

      - name: Kontrola typů
        run: pnpm type-check

      - name: Debug versions
        run: |
          node --version
          npm --version
          npx prisma --version

      # - name: Spuštění testů
      # run: pnpm test --passWithNoTests

      - name: Build projektu
        run: pnpm build
