name: P콏id치n칤 zpr치vy p콏i uzav콏en칤 issue

on:
  issues:
    types:
      - closed

jobs:
  add-comment:
    name: P콏id치n칤 koment치콏e
    if: github.event.issue.state_reason == 'completed'
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: read
    steps:
      - name: P콏idat koment치콏 k uzav콏en칠 issue
        uses: actions/github-script@v7
        with:
          script: |
            const issue_number = context.issue.number;
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const message = `
            D캩kujeme za nahl치코en칤! 游꿀

            Tato issue byla uzav콏ena jako **vy콏e코en치**. Pokud probl칠m p콏etrv치v치 nebo se znovu objev칤, nev치hejte issue znovu otev콏칤t nebo vytvo콏it novou.
            `;
            await github.rest.issues.createComment({
              owner,
              repo,
              issue_number,
              body: message
            });
